# Introduction {-}

The Bahamas Research and Access and Benefit-Sharing Permit System provides a one stop shop to obtain all the main permits needed to conduct research involving biodiversity and genetic resources in the Bahamas. As you complete the application the system will automatically determine which standard permits you need and pre-fill them for you. We also provide information on specialist permits that you may require. Your profile and pre-filled permits will then be sent to desk officers at DEPP who will direct your application to the appropriate departments.

The system is designed to streamline the application process, making it easy to apply for all the major permits associated with typical research projects. At the same time, the system addresses access to genetic resources and benefit-sharing under the [Nagoya Protocol](https://www.cbd.int/abs/) of the [United Nations Convention on Biological Diversity](https://www.cbd.int/). This involves a contractual agreement between your home institution and the government of the Bahamas in the interest of ensuring equitable outcomes for researchers and communities and biodiversity in the Bahamas.