# Registering with the System {-}

_Status: Working Draft_

When registering you will create a free username and password with your email address. 

The system also requires all applicants to provide a free [ORCID](https://orcid.org/) identifier. 

ORCID is a free persisent researcher identifier that stays with a researcher throughout their careers. An ORCID profile is under the control of the researcher themselves and they can choose to make information public or private. 

The advantage of ORCID ids for researchers are that they allow information on their employment, research funding and publications to be stored in one place. In particular, the publication profile can be automatically updated through services such as Crossref. This makes it easier for us to create an electronic archive of research publications about the Bahamas and reduces the need to send emails. 

### Passport Instructions {-#passport}

You are required to provide a pdf copy of your current passport as part of the registration process. 

### Passport Photo Requirements {-#passport-photo}
You are required to provide a passport photo as part of the registration process. The passport photo should be the standard size for the Bahamas and is the same as in the United States and European Union countries. 

__Electronic images requirements__

- Format should be jpeg or png
- 600 pixels by 600 pixels minimum and maximum 1200 by 1200 pixels. 
- The image must be in colour (24 bits per pixel) in sRGB colour space. 

Many high street services offer this kind of service and will email a photo to you.

__Scanning an Existing Image__

If you are scanning an existing image the photo itself must be:

- 51mm x 51mm (2 x 2 inches)
- Scanned at a resultion of 300 pixels per inche (or 12 pixels per millimeter)

## Your Home Page {-#your-applicant-home-page}

When you have logged into the system you will find yourself at your home page. This allows you to create new applications, to retrieve the details of existing applications and review invoices for application fees. 

## Communications with Desk Officers {-#communications-with-desk-officers}

The desk officers at permit granting authorities may need to contact you with questions such as on locations, the size of samples, methods etc. 

This is handled over emails generated by the system. These communications are automatically stored as part of the file history for the application. 


