# Project Information

_Status: Working Draft_

In this step you provide information about your project. 

## You Are Applying As

In answering this question you have the option to apply as:

- A Company
- A Consortium (a consortium is a group of public or private entities)
- An Individual
- A Research Institution
- A Student

Please choose the category that most accurately affects your status as an applicant. 

The application form is the same regardless of the category of applicant. 

- If you are part of a consortium we will ask for details of the entities involved in the consortium
- If you are a company planning to conduct commercial research on biodiversity and/or traditional knowledge the application requirements are the same but the contractual provisions in the access and benefit-sharing agreement will normally be tailored to your project. 
- Applicants involved in a consortium will be asked to provide details of the entities involved in the consortium. We will require details of all public and private entities participating in a consortium. 

## Institution Details

**Name of the Institution** is the name formally used for your institution. **Institution Contact Person** This is the legal officer (such as the contracts officer) who has authority to sign contracts on behalf of the institution. Unless you are that person you should not place your name here. Researchers are agents of their employers and do not normally possess legal authority to sign on behalf of the institution. **Institutution Legal Registration Number** is the number or identifier used on the regisration certificate for your organisation (e.g. as used by Companies House or equivalent).

## Principal Researcher Details

If you are the principal researcher or team leader you need to provide the name and contact details of each member of your research team. The individuals will then be invited to register on the system and answer the relevant questions. The individual will then be associated with the issued permits.

Where an individual team member is from a different institution, their legal officer will be required to sign the ABS agreement.

Note that **all members of the research team must be named individuals** or processing of the application will be delayed for clarification.

## Research project Details

If you have previously received a permit for research in the Bahamas please provide the number of the most recent permit that you received.

**Research Project Description** This is a short abstract describing the project. It should be written in a form that is suitable for the general public to read.

**-Research Project Source of Funding** Please give the full name of the research funding possible.

**Proposed Project Start Date**. This is the formal start data of the research project. It is not the start date of your proposed research in the Bahamas.

**Proposed Project Completion Date** This is the formal end date of the research project. It is not your proposed date of your departure from the Bahamas.

**Research Project Grant Number**. This is the unique identifier awarded to your research grant when awarded by the funding agency. If you are presently at the application stage please use the application number.

## Equipment

These questions only apply in circumstances where you are seeking to make duty-free imports of equipment. The term equipment does not apply to expendable supplies (food, fuels or other consumable materials etc.)
