# Benefit-Sharing

The United Nations Convention on Biological Diversity (CBD) introduced the concept of benefit-sharing arising from the utilisation of genetic resources. In 2010 governments who are parties to the CBD adopted _The Nagoya Protocol on Access to Genetic Resources and the Fair and Equitable Sharing of Benefits Arising from their Utilization._ Under the Nagoya Protocol governments may agree to grant prior informed consent to access genetic resources within their jurisdictions and to establish what are known as "mutually agreed terms" in the form of a contract on benefit-sharing with those seeking to use these resources for commercial or non-commercial purposes. An Annex to the Nagoya Protocol provides an indicative list of [Monetary and Non-monetary Benefits](https://www.cbd.int/abs/text/articles/?sec=abs-37) that is useful in considering forms of benefit-sharing. 

On a wider level, it is reasonable to expect that research conducted in a country will be beneficial to that country in some way. We aim, as far as possible, to _quantify_ the benefits that proposed research will bring to The Bahamas. 

In practice, this means that _all applicants_ seeking to conduct research in the Bahamas are required to set out the benefits that will be shared. Benefit-sharing as a concept can be considered similar to _research impact_ or _project legacy_ in that research is expected to have positive impacts for biodiversity and the communities of the Bahamas. This section of the application form asks you to quantify those benefits. 

The estimated figure for benefit sharing is not an estimate of the general value accruing from the project (monetary or otherwise) rather it is an estimate of how much money will be spent in The Bahamas in the course of the project through defined activities and, where relevant, what will be shared with The Bahamas after the project. We are mindful that predicted costs of benefit sharing may change due to circumstances. However it is expected that applicants will make reasonable estimates and attempt to follow them through to the best of their ability. Please bear in mind that the data on benefit-sharing will form part of the contract negotiated with your institution. As such please make realistic assessments. 

Benefit-sharing can take many forms and is commonly divided into *monetary* and *non-monetary* forms. Researchers seeking to conduct research in the Bahamas may also be at different stages in their careers with different means and budgets. Our expectations about benefit-sharing will recognise the diversity of means and will be proportionate to the means available to the individual and to the project. Our aim is to ensure a measurable return to the conservation of biodiversity in the Bahamas and for the benefit of Bahamian communities.  

Expectations of researcher contribution will be assessed in accordance with their career status:

1. **Early stage researchers** (such as undergraduates, masters students and PhD candidates) will be expected to think about how to offer benefits in kind. These might include contributions to community activities during the course of a research project or organising local events (such as a Cafe Scientifique) that contribute to community knowledge and understanding of biodiversity related research or benefit communities in the Bahamas in other ways. 

Researchers in this group are invited to list proposed activities and to provide estimates of the monetary value or its equivalent. 

2. **Established researchers** will generally hold significant research grants and may manage research teams. Researchers in this group may also lead or form part of consortiums of organisations including private sector entities. 

Researchers in this grouping will be expected to provide clear, quantifiable evidence of direct benefit-sharing in the Bahamas that will leave a measurable legacy. This should be reflected in budget allocations and the ability to calculate the percentage of the overall budget that will be spent on benefit sharing in the Bahamas.

Research activities involving benefit-sharing may include, but are not limited to:

- Workshops
- Training courses
- Conferences
- Exchange Visits
- Undergraduate, Masters, and PhD studentships
- Equipment that remains in the Bahamas
- Shared authorship of data and data products arising from research
- Joint publications with local researchers (including publication costs for open access publications)
- Joint ownership or control of intellectual property (know how, trade secrets, patents, copyright, trademarks, _sui generis_ database rights) arising from the utilisation of genetic resources

The distinction between purely non-commercial and commercial research has become increasingly blurred as a result of a drive to promote income generation from research activity (e.g. arising from the Bayh-Dole Act). Applications that involve a commercial dimension will be expected to be explicit about proposed benefit-sharing with DEPP and the Government of the Bahamas. 

Researchers whose work is explicitly commercial, involves a commercial dimension or commercial entities are encouraged to engage in consultations with DEPP at an early stage to facilitate agreement on an ABS contract.  

3. **Commercial Activities**

Companies seeking to conduct research in the Bahamas are encouraged to contact DEPP at an early stage to discuss the terms of a possible contractual agreement. In addition to the options mentioned above, the following indicative list, provided with the Nagoya Protocol in connection with biodiversity and genetic resources, may assist companies when entering into discussions with DEPP: 

- Access fees/fee per sample collected or otherwise acquired;
- Up-front payments;
- Milestone payments;
- Payment of royalties;
- Licence fees in case of commercialization;
- Special fees to be paid to trust funds supporting conservation and sustainable use of biodiversity;
- Salaries and preferential terms where mutually agreed;
- Research funding;
- Joint ventures;
- Joint ownership (or control) of relevant intellectual property rights.

Companies should note that while there will be an expectation of monetary benefit-sharing, non-monetary forms of benefit-sharing may also feature in an agreement. 
