# Benefit-Sharing

_Status: Working Draft_

The United Nations Convention on Biological Diversity (CBD) introduced the concept of benefit-sharing arising from the utilisation of genetic resources. In 2010 governments who are parties to the CBD adopted The Nagoya Protocol on Access to Genetic Resources and the Fair and Equitable Sharing of Benefits Arising from their Utilization. 

Under the Nagoya Protocol governments may agree to grant prior informed consent to access genetic resources within their jurisdictions and to establish what are known as "mutually agreed terms" on benefit-sharing with those seeking to use these resources for commercial or non-commercial purposes. An Annex to the Nagoya Protocol provides an indicative list of [Monetary and Non-monetary Benefits](https://www.cbd.int/abs/text/articles/?sec=abs-37) that is useful in considering forms of benefit-sharing. 

<!--- No Status: What this means in practice is that all applicants seeking to conduct research involving biodiversity or the traditional knowledge of communities in the Bahamas are required to set out the benefits that will be shared. 

Benefit-sharing can be considered to be similar to the concepts of research impact or project legacy in so far that research is expected to have positive impacts.

Benefit-sharing can take many forms. Researchers seeking to conduct research in the Bahamas may also be at different stages in their careers, with different means and budgets. Our expectations about benefit-sharing will recognise the diversity of means and will be proportionate to the means available to the individual and to the project. Our aim is to ensure a measurable return to the conservation of biodiversity in the Bahamas and its communities.  

Benefit-sharing can take many forms and is commonly divided into monetary and non-monetary forms. 

1. Early stage researchers (such as undergraduates, masters and PhD students) will be expected to think about how to offer benefits in kind. These might include contributions to community activities during your research, organising local events during your stay (such as a Cafe Scientifique) that contribute to community knowledge and understanding of biodiversity related research or benefit communities in the Bahamas in other ways. 

Researchers in this group are invited to list proposed activity and to provide estimates of the monetary value or its equivalent. 

2. Established researchers will generally hold significant research grants and manage research teams. Researchers in this group may also lead or form part of consortiums of organisations including private sector entities. 

Reseachers in this grouping will be expected to provide clear, quantifiable evidence of direct benefit-sharing in the Bahamas that will leave a measurble legacy in the . This should be reflected in budget allocations and the ability to calculate the percentage of the overall budget that will be spent in the Bahamas. 

Research activities involving benefit-sharing may include, but are not limited to:

- Workshops
- Training courses
- Conferences
- Exchange Visits
- Undergraduate, Masters, and PhD studentships
- Equipment that remains in the Bahamas
- Shared authorship of data and data products arising from research
- Joint publications with local researchers (including publication costs for open access publications)
- Joint ownership or control of intellectual property (know how, trade secrets, patents, copyright, trademarks) arising from the utilisation of genetic resources

The distinction between purely non-commercial and commercial research has become increasingly fuzzy in the context of the drive to promote income generation from research activity (e.g. arising from the Bayh-Dole Act). 

Applications that involve a commercial dimension will be expected to be explicit about proposed benefit-sharing with the government of the Bahamas.

3. Commercial Activities

Companies seeking to conduct research on biodiversity and genetic resources in --->







