--- 
title: "Bahamas Guide for Applicants for Research and ABS Permits"
author: ""
date: "04-05-2021"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "Guide for Applicants for the Bahamas Research and Access and Benefit-Sharing Permit System."
---

# Welcome {-}

Welcome to the Bahamas Research Permit and Access and Benefit Sharing (ABS) System guide for applicants.

This guide has been prepared as a practical guide to assist you through each step of the online research permit and ABS system. The guide will take you through:

- Documents you need to provide
- Each step in the online system
- Expectations about project impact and benefit-sharing under the Nagoya Protocol

This is a practical guide to applying for a research permit in the Bahamas through its online system. The guide will be periodically revised and updated. __In all cases guidance from the government authorities in the Bahamas is authoritative over the contents of this guide__. This guide is also not a guide to the laws and regulations of the Bahamas. Applicants seeking clarification on legal issues are advised to contact the appropriate authorities in the Bahamas and to seek appropriate specialist legal advice.  